using System.Collections.Generic;
using RuntimeUnityEditor.Core.MaterialEditor.Keywords;

namespace RuntimeUnityEditor.Core.MaterialEditor.Properties
{
    public static class MaterialEditorPropertyKeywords
    {
        public static Dictionary<MaterialEditorProperties, MaterialEditorKeywords[]> KEYWORDS = new Dictionary<MaterialEditorProperties, MaterialEditorKeywords[]>
        {
            { MaterialEditorProperties.Color, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.Color2, new[] { MaterialEditorKeywords.UWE_3COLOR } },
            { MaterialEditorProperties.Color3, new[] { MaterialEditorKeywords.UWE_3COLOR  } },
            { MaterialEditorProperties.Mode, new[] { MaterialEditorKeywords.UWE_SIG, MaterialEditorKeywords.MARMO_SPECMAP } },
            { MaterialEditorProperties.Fresnel, new[] { MaterialEditorKeywords.UWE_SIG, MaterialEditorKeywords.MARMO_SPECMAP } },
            { MaterialEditorProperties.Shininess, new[] { MaterialEditorKeywords.UWE_SIG, MaterialEditorKeywords.MARMO_SPECMAP } },
            { MaterialEditorProperties.SpecInt, new[] { MaterialEditorKeywords.UWE_SIG, MaterialEditorKeywords.MARMO_SPECMAP } },
            { MaterialEditorProperties.EnableGlow, new[] { MaterialEditorKeywords.MARMO_EMISSION } },
            { MaterialEditorProperties.EnableLighting, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.SpecColor, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.SrcBlend, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.DstBlend, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.SrcBlend2, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.DstBlend2, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.AddSrcBlend, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.AddDstBlend, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.AddSrcBlend2, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.AddDstBlend2, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.EnableMisc, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.ZWrite, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.ZOffset, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.EnableCutOff, new[] { MaterialEditorKeywords.MARMO_ALPHA_CLIP } },
            { MaterialEditorProperties.Cutoff, new[] { MaterialEditorKeywords.MARMO_ALPHA_CLIP, MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.EnableDitherAlpha, new[] { MaterialEditorKeywords.UWE_DITHERALPHA } },
            { MaterialEditorProperties.EnableVrFadeOut, new[] { MaterialEditorKeywords.UWE_VR_FADEOUT } },
            { MaterialEditorProperties.IBLreductionAtNight, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.EnableSimpleGlass, new[] { MaterialEditorKeywords.MARMO_SIMPLE_GLASS } },
            { MaterialEditorProperties.EnableVertexColor, new[] { MaterialEditorKeywords.MARMO_VERTEX_COLOR } },
            { MaterialEditorProperties.EnableSchoolFish, new[] { MaterialEditorKeywords.UWE_SCHOOLFISH } },
            { MaterialEditorProperties.EnableMainMaps, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.GlowColor, new MaterialEditorKeywords[] {  } },
            { MaterialEditorProperties.GlowUVfromVC, new[] { MaterialEditorKeywords.GLOW_UV_FROM_VERTECCOLOR, MaterialEditorKeywords.MARMO_EMISSION } },
            { MaterialEditorProperties.GlowStrength, new[] { MaterialEditorKeywords.MARMO_EMISSION, MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.GlowStrengthNight, new[] { MaterialEditorKeywords.MARMO_EMISSION, MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.EmissionLM, new[] { MaterialEditorKeywords.MARMO_EMISSION, MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.EmissionLMNight, new[] { MaterialEditorKeywords.MARMO_EMISSION, MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.EnableDetailMaps, new[] { MaterialEditorKeywords.UWE_DETAILMAP } },
            { MaterialEditorProperties.DetailIntensities, new[] { MaterialEditorKeywords.UWE_DETAILMAP } },
            { MaterialEditorProperties.EnableLightmap, new[] { MaterialEditorKeywords.UWE_LIGHTMAP } },
            { MaterialEditorProperties.LightmapStrength, new[] { MaterialEditorKeywords.UWE_LIGHTMAP } },
            { MaterialEditorProperties.Enable3Color, new[] { MaterialEditorKeywords.UWE_3COLOR } },
            { MaterialEditorProperties.SpecColor2, new[] { MaterialEditorKeywords.UWE_3COLOR } },
            { MaterialEditorProperties.SpecColor3, new[] { MaterialEditorKeywords.UWE_3COLOR } },
            { MaterialEditorProperties.DeformParams, new[] { MaterialEditorKeywords.FX_DEFORM, MaterialEditorKeywords.FX_MESMER, MaterialEditorKeywords.FX_BLEEDER } },
            { MaterialEditorProperties.FillSack, new[] { MaterialEditorKeywords.FX_BLEEDER } },
            { MaterialEditorProperties.OverlayStrength, new[] { MaterialEditorKeywords.FX_PROPULSIONCANNON } },
            { MaterialEditorProperties.GlowScrollColor, new[] { MaterialEditorKeywords.FX_PROPULSIONCANNON } },
            { MaterialEditorProperties.Hypnotize, new[] { MaterialEditorKeywords.FX_MESMER } },
            { MaterialEditorProperties.ScrollColor, new[] { MaterialEditorKeywords.FX_MESMER, MaterialEditorKeywords.FX_BLEEDER } },
            { MaterialEditorProperties.ColorStrength, new[] { MaterialEditorKeywords.FX_MESMER, MaterialEditorKeywords.FX_BLEEDER } },
            { MaterialEditorProperties.GlowMaskSpeed, new[] { MaterialEditorKeywords.FX_ANIMATEDGLOW } },
            { MaterialEditorProperties.ScrollSpeed, new[] { MaterialEditorKeywords.FX_MESMER, MaterialEditorKeywords.FX_BLEEDER, MaterialEditorKeywords.FX_PROPULSIONCANNON } },
            { MaterialEditorProperties.DetailsColor, new[] { MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.SquaresColor, new[] { MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.SquaresTile, new[] { MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.SquaresSpeed, new[] { MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.SquaresIntensityPow, new[] { MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.NoiseSpeed, new[] { MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.FakeSSSparams, new[] { MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.FakeSSSSpeed, new[] { MaterialEditorKeywords.FX_IONCRYSTAL } },
            { MaterialEditorProperties.BorderColor, new[] { MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.Built, new[] { MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.BuildParams, new[] { MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.BuildLinear, new[] { MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.NoiseThickness, new[] { MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.NoiseStr, new[] { MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.Scale, new[] { MaterialEditorKeywords.UWE_WAVING, MaterialEditorKeywords.FX_ROPE, MaterialEditorKeywords.FX_SINWAVE, MaterialEditorKeywords.FX_KELP } },
            { MaterialEditorProperties.Frequency, new[] { MaterialEditorKeywords.UWE_WAVING, MaterialEditorKeywords.FX_ROPE, MaterialEditorKeywords.FX_SINWAVE, MaterialEditorKeywords.FX_KELP } },
            { MaterialEditorProperties.Speed, new[] { MaterialEditorKeywords.UWE_WAVING, MaterialEditorKeywords.FX_ROPE, MaterialEditorKeywords.FX_SINWAVE, MaterialEditorKeywords.FX_KELP } },
            { MaterialEditorProperties.ObjectUp, new[] { MaterialEditorKeywords.UWE_WAVING } },
            { MaterialEditorProperties.WaveUpMin, new[] { MaterialEditorKeywords.UWE_WAVING } },
            { MaterialEditorProperties.Fallof, new[] { MaterialEditorKeywords.UWE_WAVING, MaterialEditorKeywords.FX_ROPE } },
            { MaterialEditorProperties.RopeGravity, new[] { MaterialEditorKeywords.FX_ROPE } },
            { MaterialEditorProperties.minYpos, new[] { MaterialEditorKeywords.FX_KELP, MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.maxYpos, new[] { MaterialEditorKeywords.FX_KELP, MaterialEditorKeywords.FX_BUILDING } },
            { MaterialEditorProperties.EnableBurst, new[] { MaterialEditorKeywords.FX_BURST } },
            { MaterialEditorProperties.Displacement, new[] { MaterialEditorKeywords.FX_BURST } },
            { MaterialEditorProperties.BurstStrength, new[] { MaterialEditorKeywords.FX_BURST } },
            { MaterialEditorProperties.Range, new[] { MaterialEditorKeywords.FX_BURST } },
            { MaterialEditorProperties.ClipRange, new[] { MaterialEditorKeywords.FX_BURST } },
            { MaterialEditorProperties.EnableInfection, new[] { MaterialEditorKeywords.UWE_INFECTION } },
            { MaterialEditorProperties.EnablePlayerInfection, new[] { MaterialEditorKeywords.UWE_PLAYERINFECTION } },
            { MaterialEditorProperties.InfectionHeightStrength, new[] { MaterialEditorKeywords.UWE_INFECTION, MaterialEditorKeywords.UWE_PLAYERINFECTION } },
            { MaterialEditorProperties.InfectionScale, new[] { MaterialEditorKeywords.UWE_INFECTION, MaterialEditorKeywords.UWE_PLAYERINFECTION } },
            { MaterialEditorProperties.InfectionOffset, new[] { MaterialEditorKeywords.UWE_INFECTION, MaterialEditorKeywords.UWE_PLAYERINFECTION } },
            { MaterialEditorProperties.InfectionSpeed, new[] { MaterialEditorKeywords.UWE_PLAYERINFECTION } },
            { MaterialEditorProperties.MyCullVariable, new MaterialEditorKeywords[] {  } }
        };
    }
}