using RuntimeUnityEditor.Core.MaterialEditor.Properties.Types;
using System.Collections.Generic;

namespace RuntimeUnityEditor.Core.MaterialEditor.Properties
{
    public static class MaterialEditorPropertyTypes
    {
        public static Dictionary<MaterialEditorProperties, MaterialEditorPropertyType> TYPES = new Dictionary<MaterialEditorProperties, MaterialEditorPropertyType>()
        {
            { MaterialEditorProperties.Color, new MaterialEditorPropertyColor("_Color") },
            { MaterialEditorProperties.Color2, new MaterialEditorPropertyColor("_Color2") },
            { MaterialEditorProperties.Color3, new MaterialEditorPropertyColor("_Color3") },
            { MaterialEditorProperties.Mode, new MaterialEditorPropertyFloat("_Mode", 0.0f, 100f) },
            { MaterialEditorProperties.Fresnel, new MaterialEditorPropertyFloat("_Fresnel", 0.0f, 1f) },
            { MaterialEditorProperties.Shininess, new MaterialEditorPropertyFloat("_Shininess", 2f, 8f) },
            { MaterialEditorProperties.SpecInt, new MaterialEditorPropertyFloat("_SpecInt", 0.0f, 50f) },
            { MaterialEditorProperties.EnableGlow, new MaterialEditorPropertyToggle("_EnableGlow") },
            { MaterialEditorProperties.EnableLighting, new MaterialEditorPropertyToggle("_EnableLighting") },
            { MaterialEditorProperties.SpecColor, new MaterialEditorPropertyColor("_SpecColor") },
            { MaterialEditorProperties.SrcBlend, new MaterialEditorPropertyFloat("_SrcBlend") },
            { MaterialEditorProperties.DstBlend, new MaterialEditorPropertyFloat("_DstBlend") },
            { MaterialEditorProperties.SrcBlend2, new MaterialEditorPropertyFloat("_SrcBlend2") },
            { MaterialEditorProperties.DstBlend2, new MaterialEditorPropertyFloat("_DstBlend2") },
            { MaterialEditorProperties.AddSrcBlend, new MaterialEditorPropertyFloat("_AddSrcBlend") },
            { MaterialEditorProperties.AddDstBlend, new MaterialEditorPropertyFloat("_AddDstBlend") },
            { MaterialEditorProperties.AddSrcBlend2, new MaterialEditorPropertyFloat("_AddSrcBlend2") },
            { MaterialEditorProperties.AddDstBlend2, new MaterialEditorPropertyFloat("_AddDstBlend2") },
            { MaterialEditorProperties.EnableMisc, new MaterialEditorPropertyToggle("_EnableMisc") },
            { MaterialEditorProperties.ZWrite, new MaterialEditorPropertyToggle("_ZWrite") },
            { MaterialEditorProperties.ZOffset, new MaterialEditorPropertyFloat("_ZOffset") },
            { MaterialEditorProperties.EnableCutOff, new MaterialEditorPropertyToggle("_EnableCutOff") },
            { MaterialEditorProperties.Cutoff, new MaterialEditorPropertyToggle("_Cutoff") },
            { MaterialEditorProperties.EnableDitherAlpha, new MaterialEditorPropertyToggle("_EnableDitherAlpha") },
            { MaterialEditorProperties.EnableVrFadeOut, new MaterialEditorPropertyToggle("_EnableVrFadeOut") },
            { MaterialEditorProperties.IBLreductionAtNight, new MaterialEditorPropertyFloat("_IBLreductionAtNight", 0.0f, 1f) },
            { MaterialEditorProperties.EnableSimpleGlass, new MaterialEditorPropertyToggle("_EnableSimpleGlass") },
            { MaterialEditorProperties.EnableVertexColor, new MaterialEditorPropertyToggle("_EnableVertexColor") },
            { MaterialEditorProperties.EnableSchoolFish, new MaterialEditorPropertyToggle("_EnableSchoolFish") },
            { MaterialEditorProperties.EnableMainMaps, new MaterialEditorPropertyToggle("_EnableMainMaps") },
            { MaterialEditorProperties.GlowColor, new MaterialEditorPropertyColor("_GlowColor") },
            { MaterialEditorProperties.GlowUVfromVC, new MaterialEditorPropertyToggle("_GlowUVfromVC") },
            { MaterialEditorProperties.GlowStrength, new MaterialEditorPropertyFloat("_GlowStrength") },
            { MaterialEditorProperties.GlowStrengthNight, new MaterialEditorPropertyFloat("_GlowStrengthNight") },
            { MaterialEditorProperties.EmissionLM, new MaterialEditorPropertyFloat("_EmissionLM") },
            { MaterialEditorProperties.EmissionLMNight, new MaterialEditorPropertyFloat("_EmissionLMNight") },
            { MaterialEditorProperties.EnableDetailMaps, new MaterialEditorPropertyToggle("_EnableDetailMaps") },
            { MaterialEditorProperties.DetailIntensities, new MaterialEditorPropertyVector4("_DetailIntensities") },
            { MaterialEditorProperties.EnableLightmap, new MaterialEditorPropertyToggle("_EnableLightmap") },
            { MaterialEditorProperties.LightmapStrength, new MaterialEditorPropertyFloat("_LightmapStrength") },
            { MaterialEditorProperties.Enable3Color, new MaterialEditorPropertyToggle("_Enable3Color") },
            { MaterialEditorProperties.SpecColor2, new MaterialEditorPropertyColor("_SpecColor2") },
            { MaterialEditorProperties.SpecColor3, new MaterialEditorPropertyColor("_SpecColor3") },
            { MaterialEditorProperties.DeformParams, new MaterialEditorPropertyVector4("_DeformParams") },
            { MaterialEditorProperties.FillSack, new MaterialEditorPropertyFloat("_FillSack", 0.0f, 1f) },
            { MaterialEditorProperties.OverlayStrength, new MaterialEditorPropertyFloat("_OverlayStrength", 0.0f, 1f) },
            { MaterialEditorProperties.GlowScrollColor, new MaterialEditorPropertyColor("_GlowScrollColor") },
            { MaterialEditorProperties.Hypnotize, new MaterialEditorPropertyFloat("_Hypnotize", 0.0f, 1f) },
            { MaterialEditorProperties.ScrollColor, new MaterialEditorPropertyColor("_ScrollColor") },
            { MaterialEditorProperties.ColorStrength, new MaterialEditorPropertyVector4("_ColorStrength") },
            { MaterialEditorProperties.GlowMaskSpeed, new MaterialEditorPropertyVector4("_GlowMaskSpeed") },
            { MaterialEditorProperties.ScrollSpeed, new MaterialEditorPropertyVector4("_ScrollSpeed") },
            { MaterialEditorProperties.DetailsColor, new MaterialEditorPropertyColor("_DetailsColor") },
            { MaterialEditorProperties.SquaresColor, new MaterialEditorPropertyColor("_SquaresColor") },
            { MaterialEditorProperties.SquaresTile, new MaterialEditorPropertyFloat("_SquaresTile", 0.0f, 100f) },
            { MaterialEditorProperties.SquaresSpeed, new MaterialEditorPropertyFloat("_SquaresSpeed", 0.0f, 10f) },
            { MaterialEditorProperties.SquaresIntensityPow, new MaterialEditorPropertyFloat("_SquaresIntensityPow", 0.0f, 20f) },
            { MaterialEditorProperties.NoiseSpeed, new MaterialEditorPropertyVector4("_NoiseSpeed") },
            { MaterialEditorProperties.FakeSSSparams, new MaterialEditorPropertyVector4("_FakeSSSparams") },
            { MaterialEditorProperties.FakeSSSSpeed, new MaterialEditorPropertyVector4("_FakeSSSSpeed") },
            { MaterialEditorProperties.BorderColor, new MaterialEditorPropertyColor("_BorderColor") },
            { MaterialEditorProperties.Built, new MaterialEditorPropertyFloat("_Built", 0.0f, 1f) },
            { MaterialEditorProperties.BuildParams, new MaterialEditorPropertyVector4("_BuildParams") },
            { MaterialEditorProperties.BuildLinear, new MaterialEditorPropertyFloat("_BuildLinear", 0.0f, 100f) },
            { MaterialEditorProperties.NoiseThickness, new MaterialEditorPropertyFloat("_NoiseThickness", 0.0f, 1f) },
            { MaterialEditorProperties.NoiseStr, new MaterialEditorPropertyFloat("_NoiseStr", 0.0f, 1f) },
            { MaterialEditorProperties.Scale, new MaterialEditorPropertyVector4("_Scale") },
            { MaterialEditorProperties.Frequency, new MaterialEditorPropertyVector4("_Frequency") },
            { MaterialEditorProperties.Speed, new MaterialEditorPropertyVector4("_Speed") },
            { MaterialEditorProperties.ObjectUp, new MaterialEditorPropertyVector4("_ObjectUp") },
            { MaterialEditorProperties.WaveUpMin, new MaterialEditorPropertyFloat("_WaveUpMin", 0.0f, 10f) },
            { MaterialEditorProperties.Fallof, new MaterialEditorPropertyFloat("_Fallof", 0.0f, 10f) },
            { MaterialEditorProperties.RopeGravity, new MaterialEditorPropertyFloat("_RopeGravity", 0.0f, 10f) },
            { MaterialEditorProperties.minYpos, new MaterialEditorPropertyFloat("_minYpos", 0.0f, 1f) },
            { MaterialEditorProperties.maxYpos, new MaterialEditorPropertyFloat("_maxYpos", 0.0f, 1f) },
            { MaterialEditorProperties.EnableBurst, new MaterialEditorPropertyToggle("_EnableBurst") },
            { MaterialEditorProperties.Displacement, new MaterialEditorPropertyFloat("_Displacement", 0.0f, 5f) },
            { MaterialEditorProperties.BurstStrength, new MaterialEditorPropertyFloat("_BurstStrength", 0.0f, 1f) },
            { MaterialEditorProperties.Range, new MaterialEditorPropertyVector4("_Range") },
            { MaterialEditorProperties.ClipRange, new MaterialEditorPropertyFloat("_ClipRange", 0.0f, 1f) },
            { MaterialEditorProperties.EnableInfection, new MaterialEditorPropertyToggle("_EnableInfection") },
            { MaterialEditorProperties.EnablePlayerInfection, new MaterialEditorPropertyToggle("_EnablePlayerInfection") },
            { MaterialEditorProperties.InfectionHeightStrength, new MaterialEditorPropertyFloat("_InfectionHeightStrength", 0.0f, 1f) },
            { MaterialEditorProperties.InfectionScale, new MaterialEditorPropertyVector4("_InfectionScale") },
            { MaterialEditorProperties.InfectionOffset, new MaterialEditorPropertyVector4("_InfectionOffset") },
            { MaterialEditorProperties.InfectionSpeed, new MaterialEditorPropertyVector4("_InfectionSpeed") },
            { MaterialEditorProperties.MyCullVariable, new MaterialEditorPropertyFloat("_MyCullVariable", 0.0f, 2f) },
        };
    }
}
